# !!! AUTO-MANAGED by Update-MpvEnvironment.ps1 !!!
# This file is synced from upstream hdr-toys on every update run.
# Any manual edits will be LOST on the next update.
# To customize HDR behavior, edit mpv.conf profiles instead.
#
target-colorspace-hint=no

tone-mapping=clip
gamut-mapping-mode=clip

[bt.2100-pq]
profile-cond=get("video-params/primaries") == "bt.2020" and get("video-params/gamma") == "pq"
profile-restore=copy
target-prim=bt.2020
target-trc=pq
glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/utils/clip_both.glsl
glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/transfer-function/pq_inv.glsl
glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/tone-mapping/astra.glsl
glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/gamut-mapping/jedypod.glsl
glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/transfer-function/bt1886.glsl
glsl-shader-opts-append=auto_exposure_limit_positive=1.02

[bt.2100-hlg]
profile-cond=get("video-params/primaries") == "bt.2020" and get("video-params/gamma") == "hlg"
profile-restore=copy
target-prim=bt.2020
target-trc=hlg
glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/utils/clip_both.glsl
glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/transfer-function/hlg_inv.glsl
glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/tone-mapping/astra.glsl
glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/gamut-mapping/jedypod.glsl
glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/transfer-function/bt1886.glsl

[bt.2020]
profile-cond=get("video-params/primaries") == "bt.2020" and get("video-params/gamma") == "bt.1886"
profile-restore=copy
target-prim=bt.2020
target-trc=bt.1886
glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/transfer-function/bt1886_inv.glsl
glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/gamut-mapping/jedypod.glsl
glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/transfer-function/bt1886.glsl

[linear]
profile-cond=get("file-format") == "exr_pipe" or get("file-format") == "hdr_pipe" or get("file-format") == "tiff_pipe"
profile-restore=copy
vf=format:gamma=linear
deband=no
scale=bilinear
target-prim=bt.2020
target-trc=linear
# glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/gamut-mapping/clip.glsl
glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/utils/clip_black.glsl
glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/utils/clip_alpha.glsl
glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/tone-mapping/astra.glsl
glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/gamut-mapping/jedypod.glsl
glsl-shader=C:/mpv/portable_config/shaders/hdr-toys/transfer-function/bt1886.glsl
glsl-shader-opts-append=spatial_stable_iterations=0
glsl-shader-opts-append=temporal_stable_duration=0
glsl-shader-opts-append=enable_metering=1
